swagger: '2.0'
info:
  version: 0.0.1
  title: people management api
  description: API for the management of people, their adresses and contacts
host: localhost:4444
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /person/{id}:
    get:
      parameters:
        - name: id
          in: path
          type: integer
          description: id of the person
          required: true
      responses:
        200:
          description: Person's information
          schema:
            $ref: '#/definitions/Person'
definitions:
  Person:
    type: object
    properties:
      firstname:
        type: string
      lastname:
        type: string
      birthday:
        type: integer
        format: int32
      adresses:
        type: array
        items:
          $ref: '#/definitions/Address'
  Address:
    type: object
    properties:
      adress:
        type: string
      street:
        type: string
      city:
        type: string
      state:
        type: string
      postalcode:
        type: string
      adressType:
        type: string
        enum: [shipping, billing]


